// Yahoo Finance format: SYMBOL-USD
export const CRYPTO_SYMBOLS = [
  // majors
  'BTC-USD', 'ETH-USD', 'BNB-USD', 'XRP-USD', 'SOL-USD', 'ADA-USD', 'DOGE-USD',
  'AVAX-USD', 'DOT-USD', 'MATIC-USD', 'LINK-USD', 'SHIB-USD', 'LTC-USD',
  'ATOM-USD', 'UNI-USD', 'XLM-USD', 'NEAR-USD', 'APT-USD', 'OP-USD', 'ARB-USD',
  'FIL-USD', 'HBAR-USD', 'ICP-USD', 'VET-USD', 'AAVE-USD', 'MKR-USD', 'GRT-USD',
  'INJ-USD', 'RUNE-USD', 'FTM-USD',
  // defi & l2
  'CRV-USD', 'LDO-USD', 'SNX-USD', 'COMP-USD', 'SUSHI-USD', 'YFI-USD', 'BAL-USD',
  'UMA-USD', '1INCH-USD', 'DYDX-USD', 'ENS-USD', 'RPL-USD', 'GMX-USD',
  'JUP-USD', 'PENDLE-USD', 'STRK-USD',
  // infrastructure
  'ALGO-USD', 'EGLD-USD', 'MINA-USD', 'FLOW-USD', 'KAVA-USD', 'ZEC-USD',
  'EOS-USD', 'XTZ-USD', 'THETA-USD', 'AXS-USD', 'SAND-USD', 'MANA-USD',
  'ENJ-USD', 'CHZ-USD', 'GALA-USD', 'IMX-USD', 'RNDR-USD', 'FET-USD',
  // l1 / new chains
  'SUI-USD', 'SEI-USD', 'TIA-USD', 'STX-USD', 'KAS-USD', 'TON-USD',
  'TRX-USD', 'BCH-USD', 'ETC-USD', 'NEO-USD',
  // ai & data
  'TAO-USD', 'OCEAN-USD', 'ONDO-USD', 'AGIX-USD', 'WLD-USD',
  // exchange tokens
  'CRO-USD', 'OKB-USD',
  // privacy / legacy
  'XMR-USD', 'DASH-USD', 'ZIL-USD', 'IOTA-USD',
  // misc infrastructure
  'ANKR-USD', 'STORJ-USD', 'BAT-USD', 'CELO-USD', 'ROSE-USD', 'ONE-USD',
  // meme
  'PEPE-USD', 'WIF-USD', 'BONK-USD', 'FLOKI-USD',
] as const;

// Yahoo Finance format: PAIR=X
export const FOREX_SYMBOLS = [
  // majors
  'EURUSD=X', 'GBPUSD=X', 'USDJPY=X', 'USDCHF=X', 'AUDUSD=X', 'USDCAD=X', 'NZDUSD=X',
  // crosses
  'EURGBP=X', 'EURJPY=X', 'GBPJPY=X', 'AUDJPY=X', 'CADJPY=X', 'EURAUD=X', 'EURCHF=X',
  'GBPCHF=X', 'NZDJPY=X', 'GBPAUD=X', 'EURCZD=X', 'AUDNZD=X', 'GBPCAD=X', 'AUDCAD=X',
  'CHFJPY=X', 'EURNZD=X', 'GBPNZD=X',
  // emerging markets
  'USDMXN=X', 'USDZAR=X', 'USDTRY=X', 'USDINR=X', 'USDCNY=X',
  'USDSGD=X', 'USDHKD=X', 'USDNOK=X', 'USDSEK=X', 'USDPLN=X',
  'USDDKK=X', 'USDHUF=X', 'USDCZK=X', 'USDTHB=X', 'USDIDR=X',
  'USDTWD=X', 'USDKRW=X', 'USDBRL=X', 'USDCLP=X', 'USDCOP=X',
] as const;

// Yahoo Finance format: SYMBOL=F
export const FUTURES_SYMBOLS = [
  // indices
  'ES=F', 'NQ=F', 'YM=F', 'RTY=F', 'VIX=F', 'NIKKEI=F',
  // energy
  'CL=F', 'BZ=F', 'NG=F', 'HO=F', 'RB=F',
  // metals
  'GC=F', 'SI=F', 'HG=F', 'PL=F', 'PA=F',
  // agriculture
  'ZC=F', 'ZW=F', 'ZS=F', 'ZM=F', 'ZL=F',
  'CT=F', 'KC=F', 'SB=F', 'CC=F', 'OJ=F',
  'LC=F', 'LH=F', 'FC=F', 'ZO=F', 'ZR=F', 'LBS=F',
  // bonds
  'ZB=F', 'ZN=F', 'ZF=F', 'ZT=F',
  // currency & crypto
  '6E=F', '6B=F', '6J=F', '6A=F', '6C=F', '6S=F', '6N=F', '6M=F',
  'DX=F', 'BTC=F', 'ETH=F',
] as const;

export const NASDAQ_ADDITIONAL = [
  // nasdaq-100 (not in s&p 500)
  'MELI', 'TEAM', 'LCID', 'RIVN', 'OKTA', 'ZM', 'DOCU', 'ROKU', 'NET',
  'CRSP', 'ASML', 'MRVL', 'PDD', 'JD', 'BIDU', 'NTES', 'TCOM',

  // growth & momentum
  'SOFI', 'UPST', 'AFRM', 'PATH', 'SNOW', 'DKNG', 'RBLX', 'U', 'BILL',
  'HUBS', 'TWLO', 'MDB', 'CFLT', 'GTLB', 'S', 'DUOL', 'PINS', 'SNAP',
  'SPOT', 'LYFT', 'GRAB', 'SE', 'SHOP', 'SQ', 'FUBO',

  // biotech & pharma
  'BNTX', 'NVAX', 'SGEN', 'EXAS', 'ALNY', 'SRPT', 'RARE', 'BMRN',
  'NBIX', 'IONS', 'HALO', 'LEGN', 'PCVX', 'KRYS', 'ARWR', 'BGNE',
  'VXRT', 'INO', 'SAVA', 'MGNX', 'NTLA', 'EDIT', 'BEAM', 'PRTA',
  'VCNX', 'IMVT', 'CCCC', 'RCKT', 'RVNC', 'FATE', 'GTHX', 'FOLD',
  'APLS', 'DCPH', 'ROIV', 'XNCR', 'ARQT', 'KROS', 'ARVN', 'CYTK',
  'DAWN', 'EWTX', 'HLVX', 'IMCR', 'INSM', 'ITCI', 'LGND', 'MDGL',
  'MIRM', 'NUVB', 'PTCT', 'RGNX', 'RCUS', 'SRRK', 'VCEL', 'VKTX',
  'VRNA', 'XENE', 'ZLAB', 'ACAD', 'AGEN', 'AKRO', 'ANAB', 'ARDX',
  'AUPH', 'BBIO', 'CLDX', 'CPRX', 'DVAX', 'ENTA', 'EXEL', 'FGEN',
  'GERN', 'HRTX', 'IMGN', 'IOVA', 'IRWD', 'JAZZ', 'KURA', 'MCRB',
  'NKTX', 'OLINK', 'PRAX', 'SAGE', 'TGTX', 'TVTX', 'VCYT', 'XERS',

  // tech & ai
  'ARM', 'IONQ', 'RGTI', 'AI', 'SOUN', 'BBAI', 'UPWK', 'FVRR', 'WIX',
  'ZI', 'ESTC', 'NEWR', 'ASAN', 'MNDY', 'DOCN', 'FSLY', 'AKAM', 'DBX',
  'BOX', 'SPLK', 'DOMO', 'YEXT', 'ZUO', 'APPN', 'BIGC', 'COUP',
  'FROG', 'NCNO', 'QLYS', 'TENB', 'VRNS', 'ZEN', 'CRDO', 'CWAN',
  'DLO', 'ENVX', 'GCT', 'GENI', 'IOT', 'LSPD', 'MGNI', 'NXST',
  'PAYO', 'PRFT', 'PSTG', 'QLGN', 'RPD', 'SMAR', 'SPSC', 'TASK',
  'TDOC', 'TTEC', 'VERX', 'VTEX', 'WEAV', 'WK', 'YOU', 'ZETA',
  'BASE', 'BRZE', 'CRNC', 'DV', 'EVTC', 'FRSH', 'INFA', 'JAMF',
  'LSCC', 'MANH', 'NTNX', 'PCOR', 'PEGA', 'PLAN', 'RELY', 'SEMR',
  'TOST', 'WULF', 'XPRO', 'APGE', 'AVPT', 'CLSK', 'COTY', 'CPRT',

  // semiconductors
  'WOLF', 'ACLS', 'ALGM', 'AMKR', 'AOSL', 'ASPN', 'ATOM', 'AXTI',
  'CAMT', 'CRUS', 'DIOD', 'FORM', 'INDI', 'IPGP', 'ISSI', 'ITOS',
  'KLIC', 'LEDS', 'LITE', 'MASI', 'MKSI', 'MTSI', 'NOVT', 'NXPI',
  'OLED', 'ONTO', 'PLAB', 'POWI', 'QRVO', 'RMBS', 'SITM', 'SLAB',
  'SMTC', 'SYNA', 'TER', 'UCTT', 'VECO', 'VIAV', 'VSH', 'WRAP',

  // consumer & retail
  'FIVE', 'OLLI', 'RH', 'W', 'CHWY', 'CPNG', 'BABA', 'BGFV', 'BIRD',
  'BOOT', 'BROS', 'CAKE', 'CARS', 'CASA', 'CATO', 'CONN', 'COUR',
  'CURV', 'EAT', 'ELF', 'EVRI', 'FIZZ', 'FOXF', 'FRPT', 'FTDR',
  'GOOS', 'GPRO', 'HAIN', 'HIBB', 'HZO', 'IMKTA', 'JACK', 'LANC',
  'LCUT', 'LEVI', 'LOVE', 'MCBC', 'MED', 'MELI', 'MNST', 'NATH',
  'NCLH', 'ONON', 'ORLY', 'PTON', 'REAL', 'RMNI', 'SABR', 'SAVE',
  'SCVL', 'SHAK', 'SITE', 'SFIX', 'SKYW', 'SNBR', 'SPTN', 'SSYS',
  'STNE', 'SWBI', 'TACO', 'TAST', 'TNET', 'TRIP', 'TXRH', 'VIR',
  'VRNT', 'VSCO', 'WINA', 'WING', 'WOOF', 'WW', 'YELP', 'YETI',

  // ev & clean energy
  'NIO', 'XPEV', 'LI', 'FSR', 'GOEV', 'WKHS', 'HYLN', 'CHPT', 'BLNK',
  'EVGO', 'QS', 'PLUG', 'FCEL', 'BE', 'SEDG', 'RUN', 'ARRY', 'BLDP',
  'CLNE', 'ENVX', 'EVEX', 'FLNC', 'FREY', 'GEVO', 'HYZN', 'LEV',
  'LILM', 'MVST', 'NKLA', 'NOVA', 'OUST', 'PTRA', 'REE', 'RMO',
  'SHLS', 'SLDP', 'SPWR', 'STEM', 'VLD', 'XL', 'AEHR', 'AMPX',
  'AMPS', 'ARBE', 'ARVL', 'BEEM', 'CALX', 'DRIV', 'EOSE', 'FFIE',
  'FUV', 'LAZR', 'LCID', 'MULN', 'PLTK', 'PODD', 'PRCH', 'SLDP',

  // fintech & financial
  'MSTR', 'VIRT', 'ALLY', 'AX', 'BFAM', 'BL', 'BSIG', 'CACC',
  'CASH', 'CBSH', 'CFFN', 'COOP', 'CUBI', 'CWCO', 'CZFS', 'DCOM',
  'DFIN', 'DNLI', 'ENVA', 'ESNT', 'EQBK', 'FBIZ', 'FCBP', 'FCNCA',
  'FFIC', 'FISI', 'FMBH', 'FNLC', 'FRHC', 'FRME', 'FSBW', 'GBCI',
  'GNW', 'HFWA', 'HOPE', 'HTLF', 'IBTX', 'INBK', 'INDB', 'ITIC',
  'KREF', 'LADR', 'LC', 'LMND', 'LOAN', 'LPRO', 'LX', 'MCBS',
  'MKTW', 'ML', 'NBHC', 'NCR', 'NWBI', 'NYCB', 'OZK', 'PACW',
  'PATK', 'PFSI', 'PNFP', 'PRDO', 'PRSP', 'RKT', 'RILY', 'SBNY',
  'SIVB', 'SLQT', 'SNEX', 'SYF', 'TFSL', 'TREE', 'TRUP', 'UBSI',
  'UFPI', 'VBTX', 'VLY', 'VRTS', 'WABC', 'WAFD', 'WAL', 'WBS',
  'WRLD', 'WSBC', 'WTBA', 'WTFC', 'XNCR',

  // media & entertainment
  'PARA', 'BMBL', 'ATVI', 'CARG', 'CHDN', 'CNK', 'CPRI', 'CROX',
  'CWST', 'DXPE', 'EYE', 'FOSL', 'GIII', 'GRPN', 'HAFC', 'HLI',
  'IMAX', 'INSW', 'LAUR', 'LINC', 'LIND', 'LNW', 'LPTH', 'LSXMA',
  'LSXMK', 'MARA', 'NAVI', 'NXGN', 'OPRA', 'PENN', 'PLYA', 'PRGS',
  'QNST', 'RCII', 'RIOT', 'SIRI', 'SONO', 'SPHR', 'STAA', 'STRA',
  'STRR', 'TARS', 'TME', 'TRMK', 'TUYA', 'WMG', 'WWE', 'XMTR', 'ZUMZ',

  // communications & telecom
  'LUMN', 'FYBR', 'USM', 'SATS', 'GSAT', 'IRDM', 'ASTS', 'BAND',
  'BCOV', 'CALX', 'CASA', 'CCOI', 'CIEN', 'CIIG', 'CLFD', 'CNSL',
  'COMM', 'CRNT', 'CTL', 'DZSI', 'EXTR', 'GILT', 'GOGO', 'HLIT',
  'IDCC', 'INFN', 'INSG', 'LILA', 'LILAK', 'LTRX', 'LUMEN', 'MAXR',
  'MTCR', 'NTGR', 'OOMA', 'PDCO', 'RBBN', 'RDWR', 'SIFY', 'SPTN',
  'SWIR', 'TZOO', 'UBNT', 'UI', 'UTI', 'VSAT', 'WSTC', 'ZGID',

  // industrial & transportation
  'SAIA', 'LSTR', 'WERN', 'KNX', 'SNDR', 'AAWW', 'ABUS', 'ACHC',
  'ACLE', 'ACMR', 'AEIS', 'AGYS', 'AIMC', 'ALEX', 'ALGN', 'ALGT',
  'AMRC', 'AMSC', 'AMWD', 'ANGI', 'ANIP', 'APEI', 'APOG', 'ARCB',
  'ARGO', 'AROC', 'ARWR', 'ATEC', 'ATGE', 'ATLC', 'ATNI', 'AVAV',
  'AVID', 'AXGN', 'AY', 'AZPN', 'BANF', 'BCO', 'BECN', 'BJRI',
  'BKNG', 'BLD', 'BLDR', 'BLX', 'BMI', 'BRP', 'BRSP', 'CAKE',
  'CALM', 'CASY', 'CBZ', 'CDNA', 'CFX', 'CGNX', 'CHCO', 'CHE',
  'CHTR', 'CINF', 'CIR', 'CLAR', 'CLBK', 'CLSK', 'CMCO', 'CMT',
  'COHU', 'COLM', 'CPSI', 'CRAI', 'CRI', 'CSL', 'CSOD', 'CVCO',
  'CVLT', 'CWST', 'CYRX', 'CZR', 'DAN', 'DENN', 'DGII', 'DHC',
  'DIOD', 'DLB', 'DNKN', 'DOOR', 'DY', 'ECHO', 'EEFT', 'EGBN',
  'EHTH', 'EIGI', 'ENSG', 'ENVA', 'EQH', 'ESE', 'ESGR', 'ETON',
  'EVTV', 'EXLS', 'EXPO', 'FA', 'FARO', 'FCFS', 'FCN', 'FFIV',
  'FHN', 'FIGS', 'FLGT', 'FLO', 'FLWS', 'FMAO', 'FN', 'FNKO',
  'FNV', 'FOXF', 'FRO', 'FROG', 'FRPH', 'FRSH', 'FTI', 'FTNT',
  'FWRD', 'GBX', 'GCT', 'GDOT', 'GFF', 'GLBE', 'GLDD', 'GLNG',
  'GLOB', 'GLPI', 'GLW', 'GNTX', 'GO', 'GRBK', 'GRFS', 'GSHD',
  'GTBIF', 'GTX', 'GVA', 'HA', 'HAIN', 'HBB', 'HBNC', 'HEES',
  'HGV', 'HLNE', 'HLX', 'HMN', 'HMST', 'HNI', 'HRMY', 'HSC',
  'HTLD', 'HUBG', 'HURN', 'HWC', 'HWKN', 'HZNP', 'IAA', 'IART',
  'ICAD', 'ICFI', 'ICUI', 'IDYA', 'IEP', 'IGT', 'IIIN', 'IIIV',
  'IMXI', 'INGN', 'INMD', 'INST', 'INT', 'IOSP', 'IPAR', 'IRBT',
  'ISBC', 'ISSC', 'ITRI', 'IVA', 'JBSS', 'JBTX', 'JBT', 'JCOM',
  'JJSF', 'JKHY', 'JNPR', 'JOE', 'JRVR', 'JTPY', 'JW.A', 'KALU',
  'KAMN', 'KBAL', 'KELYA', 'KEQU', 'KFRC', 'KIDS', 'KLXE', 'KMDA',
  'KODK', 'KTOS', 'KURA', 'LAMR', 'LAUR', 'LAWS', 'LBC', 'LDI',
  'LFST', 'LGIH', 'LGND', 'LIVN', 'LKFN', 'LLNW', 'LMAT', 'LNDC',
  'LNTH', 'LOB', 'LOGI', 'LPRO', 'LQDA', 'LRCX', 'LSCC', 'LUNA',
  'LXRX', 'MANH', 'MATW', 'MAXN', 'MBUU', 'MBWM', 'MCBC', 'MCRI',
  'MDRX', 'MEDS', 'MESA', 'MGEE', 'MGPI', 'MGRC', 'MIDD', 'MKSI',
  'MLCO', 'MMSI', 'MNTV', 'MOD', 'MODV', 'MOGO', 'MORF', 'MORN',
  'MPWR', 'MRCY', 'MRSN', 'MRUS', 'MSEX', 'MSGS', 'MTLS', 'MTX',
  'NARI', 'NATR', 'NAVI', 'NBEV', 'NBTB', 'NCMI', 'NDSN', 'NEO',
  'NEOG', 'NGVC', 'NINE', 'NMIH', 'NMRK', 'NNBR', 'NOVN', 'NPTN',
  'NRDS', 'NSIT', 'NSTG', 'NTCT', 'NTRA', 'NUVA', 'NVCR', 'NVT',
  'NVTR', 'NWPX', 'NWS', 'NWSA', 'NX', 'NXGN', 'OABI', 'OAS',
  'OCFC', 'OCGN', 'ODP', 'OFIX', 'OFLX', 'OGS', 'OMCL', 'OMER',
  'ONB', 'OPCH', 'OPI', 'ORBC', 'ORIC', 'OSG', 'OSUR', 'OTTR',
  'ATRO', 'OVBC', 'OVID', 'PACB', 'PAGS', 'PATI', 'PATK', 'PAYA',
  'PAYS', 'PBCT', 'PBH', 'PBYI', 'PCTY', 'PDCE', 'PDFS', 'PEGA',
  'PENN', 'PETQ', 'PFG', 'PFGC', 'PGEN', 'PGNY', 'PINC', 'PKE',
  'PLAB', 'PLAY', 'PLBY', 'PLCE', 'PLUS', 'PMVP', 'PNRG', 'PNTG',
  'POWI', 'PPBI', 'PPC', 'PRAA', 'PRFT', 'PRGS', 'PRMW', 'PROS',
  'PRSC', 'PRVB', 'PSFE', 'PSMT', 'PSN', 'PSTL', 'PTGX', 'PUBM',
  'PXLW', 'QDEL', 'QLYS', 'QRTEA', 'QTRX', 'QTWO', 'QUIK', 'RAMP',
  'RAPT', 'RARE', 'RCII', 'RCKT', 'RCUS', 'RDNT', 'RDUS', 'RDVT',
  'REGI', 'REGN', 'RELL', 'REPH', 'REPL', 'RETO', 'REVG', 'RGC',
  'RGLD', 'RICK', 'RIGL', 'RIVE', 'RMBS', 'RNET', 'RNR', 'ROCC',
  'ROCK', 'ROG', 'ROLL', 'RPAY', 'RPRX', 'RRX', 'RSSS', 'RTLR',
  'RTRX', 'RUBY', 'RUSHA', 'RUSHB', 'RUTH', 'RVMD', 'RVNC', 'RVPH',
  'RYAM', 'SAIL', 'SAM', 'SANA', 'SANM', 'SBCF', 'SBFG', 'SBGI',
  'SBRA', 'SCHL', 'SCHN', 'SCOR', 'SCSC', 'SCWX', 'SDGR', 'SEAT',
  'SENEA', 'SFBS', 'SFNC', 'SGMO', 'SGMS', 'SHBI', 'SHEN', 'SHIP',
  'SHLS', 'SHOO', 'SHV', 'SIBN', 'SIG', 'SILC', 'SILK', 'SIM',
  'SITC', 'SIVB', 'SJW', 'SKIN', 'SKWD', 'SKYW', 'SLAB', 'SLDB',
  'SLP', 'SLQT', 'SMBC', 'SMID', 'SMMT', 'SMPL', 'SMSI', 'SMTX',
  'SNCR', 'SNDX', 'SNV', 'SNWV', 'SONM', 'SP', 'SPCB', 'SPFI',
  'SPNE', 'SPNT', 'SPOK', 'SPOT', 'SPRO', 'SPSC', 'SPTN', 'SPWH',
  'SPXC', 'SRCE', 'SRDX', 'SREV', 'SRNE', 'SSB', 'SSRM', 'SSTI',
  'SSTK', 'STAG', 'STBA', 'STFC', 'STLD', 'STMP', 'STNG', 'STOK',
  'STRA', 'STRL', 'STRS', 'STXS', 'SUPN', 'SUSC', 'SVRA', 'SWAV',
  'SWTX', 'SYBX', 'SYBT', 'SYNA', 'SYNC', 'SYNH', 'SYNL', 'TACO',
  'TBBK', 'TBI', 'TCBI', 'TCBK', 'TCMD', 'TDOC', 'TECH', 'TELL',
  'TENB', 'TEN', 'TERN', 'TESS', 'TFII', 'TGNA', 'TH', 'THRY',
  'TILE', 'TITN', 'TLND', 'TLYS', 'TMDX', 'TMUS', 'TNAV', 'TNDM',
  'TNXP', 'TOPS', 'TPHS', 'TPTX', 'TR', 'TRDA', 'TRIB', 'TRHC',
  'TRIP', 'TRM', 'TRMB', 'TRNO', 'TROW', 'TRS', 'TRUE', 'TRVN',
  'TTGT', 'TTM', 'TTWO', 'TWNK', 'TXG', 'TXMD', 'TXRH', 'UCBI',
  'UCTT', 'UEIC', 'UFCS', 'UFPI', 'UFPT', 'UG', 'UHAL', 'UHT',
  'UIHC', 'ULH', 'ULTA', 'UMBF', 'UNIT', 'UNTY', 'UPLD', 'URGN',
  'USAK', 'USAP', 'USAU', 'USCR', 'USIO', 'USNA', 'USPH', 'UTMD',
  'VBF', 'VCRA', 'VCYT', 'VECO', 'VEON', 'VERA', 'VERI', 'VERU',
  'VIAV', 'VICR', 'VIE', 'VIEW', 'VINC', 'VIR', 'VIRC', 'VIRI',
  'VIS', 'VITL', 'VIVO', 'VKTX', 'VLDR', 'VLY', 'VMEO', 'VNCE',
  'VNDA', 'VNE', 'VNET', 'VOXX', 'VOYA', 'VRA', 'VRRM', 'VRSK',
  'VRTS', 'VSAT', 'VSEC', 'VSH', 'VSTM', 'VTS', 'VTVT', 'VXRT',
  'WAFD', 'WASH', 'WATT', 'WBS', 'WDAY', 'WDC', 'WDFC', 'WELL',
  'WETF', 'WEYS', 'WHF', 'WIX', 'WKHS', 'WKSP', 'WLDN', 'WLK',
  'WMK', 'WNEB', 'WOR', 'WPRT', 'WRAP', 'WRBY', 'WRLD', 'WSBC',
  'WSBF', 'WSC', 'WSTG', 'WTBA', 'WTRG', 'WVVI', 'WWD', 'WWW',
  'XBIT', 'XELA', 'XENE', 'XERS', 'XLNX', 'XNCR', 'XNET', 'XOG',
  'XOMA', 'XONE', 'XPEL', 'XPER', 'XRAY', 'YGTY', 'YMAB', 'YORW',
  'YRCW', 'YSG', 'YY', 'ZBRA', 'ZEAL', 'ZEUS', 'ZIMV', 'ZION',
  'ZIXI', 'ZLAB', 'ZNTL', 'ZS', 'ZTO', 'ZUMZ', 'ZVO',

  // real estate & reits
  'REXR', 'COLD', 'IIPR', 'ADC', 'AHH', 'AIRC', 'ALEX', 'APLE',
  'BDN', 'BNL', 'BRX', 'BXP', 'CIO', 'CLPR', 'CMCT', 'CTRE',
  'CUBE', 'CUZ', 'DEA', 'DEI', 'DGRW', 'DHC', 'DOC', 'EGP',
  'ELME', 'EPR', 'ESRT', 'FAT', 'FCPT', 'FPI', 'FR', 'FSP',
  'GNL', 'GOOD', 'GPMT', 'GTY', 'HT', 'ILPT', 'INN', 'IRT',
  'IIPR', 'JBGS', 'KRC', 'LAND', 'LTC', 'MAC', 'MDRR', 'MFA',
  'MGP', 'MPW', 'NHI', 'NNN', 'NSA', 'NXRT', 'NYT', 'OFC',
  'OFFS', 'OHI', 'OUT', 'PGRE', 'PK', 'PLYM', 'PSTL', 'QTS',
  'RC', 'RLGT', 'RLJ', 'RYN', 'SAFE', 'SBRA', 'SKT', 'SLG',
  'SNDE', 'SRC', 'STAG', 'STAR', 'STOR', 'SUI', 'SVC', 'TRNO',
  'TRTX', 'UBFO', 'UBA', 'UE', 'UNIT', 'VER', 'VICI', 'VNO',
  'VRE', 'VSTA', 'WPC', 'WRI', 'WTRE', 'XHR',
] as const;

export const SP500_SYMBOLS = [
  // Mega Cap Tech
  'NVDA', 'AAPL', 'MSFT', 'AMZN', 'GOOGL', 'GOOG', 'META', 'AVGO', 'TSLA',
  // Financials & Healthcare Leaders
  'BRK-B', 'LLY', 'WMT', 'JPM', 'V', 'XOM', 'JNJ', 'ORCL', 'MA', 'MU', 'COST',
  // Tech
  'AMD', 'PLTR', 'ABBV', 'HD', 'BAC', 'NFLX', 'PG', 'CVX', 'UNH', 'KO',
  'GE', 'CSCO', 'CAT', 'MS', 'GS', 'LRCX', 'IBM', 'PM', 'WFC', 'MRK',
  'RTX', 'AMAT', 'AXP', 'TMO', 'INTC', 'MCD', 'CRM', 'LIN', 'TMUS', 'KLAC',
  'C', 'PEP', 'BA', 'DIS', 'ABT', 'ISRG', 'AMGN', 'APH', 'SCHW', 'GEV',
  'APP', 'NEE', 'TXN', 'BLK', 'ACN', 'ANET', 'UBER', 'TJX', 'GILD', 'T',
  'VZ', 'QCOM', 'DHR', 'BKNG', 'SPGI', 'INTU', 'LOW', 'ADI', 'PFE', 'HON',
  'NOW', 'DE', 'BSX', 'LMT', 'UNP', 'COF', 'SYK', 'NEM', 'MDT', 'ETN',
  'WELL', 'PANW', 'ADBE', 'COP', 'PGR', 'VRTX', 'CB', 'PLD', 'PH', 'BX',
  'CRWD', 'BMY', 'SBUX', 'KKR', 'HCA', 'CMCSA', 'CVS', 'CEG', 'ADP', 'MO',
  'CME', 'MCK', 'ICE', 'GD', 'SO', 'NKE', 'HOOD', 'NOC', 'SNPS', 'MCO',
  'WM', 'UPS', 'DUK', 'MRSH', 'DASH', 'PNC', 'FCX', 'CDNS', 'HWM', 'SHW',
  'MMM', 'USB', 'MAR', 'TT', 'ORLY', 'AMT', 'EMR', 'ELV', 'CRH', 'BK',
  'WDC', 'ABNB', 'TDG', 'MNST', 'GLW', 'ECL', 'WMB', 'REGN', 'APO', 'CMI',
  'RCL', 'EQIX', 'CTAS', 'DELL', 'STX', 'MDLZ', 'ITW', 'CI', 'GM', 'SLB',
  'AON', 'FDX', 'WBD', 'PWR', 'CL', 'JCI', 'HLT', 'COR', 'CSX', 'RSG',
  'CVNA', 'MSI', 'LHX', 'KMI', 'TEL', 'AJG', 'NSC', 'PCAR', 'TFC', 'AEP',
  'AZO', 'ROST', 'FTNT', 'TRV', 'SPG', 'EOG', 'NXPI', 'COIN', 'URI', 'APD',
  'BDX', 'ADSK', 'VLO', 'PSX', 'AFL', 'SRE', 'NDAQ', 'O', 'IDXX', 'DLR',
  'ZTS', 'VST', 'CMG', 'F', 'BKR', 'PYPL', 'MPC', 'EA', 'MPWR', 'D',
  'AME', 'ALL', 'FAST', 'CBRE', 'GWW', 'MET', 'WDAY', 'PSA', 'CAH', 'OKE',
  'TGT', 'AXON', 'EW', 'CTVA', 'CARR', 'ROK', 'AMP', 'DDOG', 'TTWO', 'EXC',
  'DAL', 'XEL', 'MSCI', 'FANG', 'ROP', 'DHI', 'OXY', 'YUM', 'EL', 'EBAY',
  'ETR', 'NUE', 'TRGP', 'KR', 'CTSH', 'LVS', 'MCHP', 'CPRT', 'IQV', 'GRMN',
  'VMC', 'FIX', 'WAB', 'MLM', 'PEG', 'AIG', 'HSY', 'A', 'PAYX', 'KDP',
  'CCI', 'PRU', 'ED', 'CCL', 'RMD', 'FICO', 'KEYS', 'SYY', 'ODFL', 'FISV',
  'GEHC', 'VTR', 'TER', 'HIG', 'WEC', 'OTIS', 'STT', 'UAL', 'EQT', 'IBKR',
  'IR', 'XYL', 'ARES', 'LYV', 'KVUE', 'KMB', 'ACGL', 'FITB', 'RJF', 'EXPE',
  'MTB', 'PCG', 'ADM', 'DG', 'HUM', 'FIS', 'EME', 'WTW', 'VICI', 'ULTA',
  'VRSK', 'ROL', 'EXR', 'CBOE', 'TSCO', 'MTD', 'TDY', 'NRG', 'HAL', 'DXCM',
  'DOV', 'HPE', 'DTE', 'CSGP', 'NTRS', 'IRM', 'LEN', 'SYF', 'STZ', 'KHC',
  'HBAN', 'BRO', 'FE', 'CFG', 'PPL', 'ATO', 'TPR', 'STLD', 'ES', 'EXE',
  'FSLR', 'HUBB', 'JBL', 'EFX', 'DLTR', 'WRB', 'STE', 'CNP', 'AWK', 'AVB',
  'PPG', 'BIIB', 'VLTO', 'OMC', 'ON', 'CHTR', 'CINF', 'LDOS', 'WSM', 'PHM',
  'DVN', 'BR', 'TPL', 'RF', 'GIS', 'DRI', 'EQR', 'EIX', 'WAT', 'KEY',
  'VRSN', 'TROW', 'SW', 'IP', 'CNC', 'CPAY', 'LULU', 'ALB', 'RL', 'CHD',
  'LH', 'BG', 'TSN', 'LUV', 'CMS', 'EXPD', 'GPN', 'L', 'NVR', 'CTRA',
  'CHRW', 'NI', 'AMCR', 'PKG', 'DGX', 'DOW', 'PFG', 'INCY', 'SBAC', 'JBHT',
  'NTAP', 'PTC', 'WY', 'SNA', 'GPC', 'PODD', 'MRNA', 'SMCI', 'IFF', 'TYL',
  'DD', 'LII', 'HPQ', 'TTD', 'PNR', 'EVRG', 'FTV', 'LNT', 'ZBH', 'WST',
  'TRMB', 'HOLX', 'TXT', 'INVH', 'APTV', 'HII', 'LYB', 'CDW', 'ESS', 'MKC',
  'J', 'TKO', 'COO', 'MAA', 'GEN', 'FOX', 'BALL', 'VTRS', 'FOXA', 'NDSN',
  'FFIV', 'IEX', 'AES', 'ALGN', 'AOS', 'ARE', 'AWI', 'BAX', 'BBWI', 'BEN',
  'BWA', 'CAG', 'CE', 'CF', 'CPB', 'CPT', 'CRL', 'CZR', 'DAY', 'DECK',
  'DFS', 'DPZ', 'ENPH', 'EPAM', 'ERIE', 'ETSY', 'FBIN', 'FDS', 'FFBC',
  'FMC', 'FRT', 'GDDY', 'GL', 'GNRC', 'HAS', 'HSIC', 'HST', 'HRL', 'HWE',
  'IPG', 'IVZ', 'JKHY', 'K', 'KIM', 'KMX', 'LEG', 'LEVI', 'LPLA', 'LW',
  'MAS', 'MGM', 'MHK', 'MKTX', 'MOH', 'MOS', 'MRO', 'MTCH', 'MTN', 'NCLH',
  'NWS', 'NWSA', 'PAYC', 'PEAK', 'PENN', 'POOL', 'REG', 'RVTY', 'SJM',
  'SPB', 'SWKS', 'TAP', 'TECH', 'TFX', 'TFS', 'TPH', 'UDR', 'UHS', 'UTHR',
  'VFC', 'WYNN', 'XPO', 'ZS',
] as const;

export const ALL_SYMBOLS = [
  ...SP500_SYMBOLS,
  ...NASDAQ_ADDITIONAL,
  ...CRYPTO_SYMBOLS,
  ...FOREX_SYMBOLS,
  ...FUTURES_SYMBOLS,
] as const;

export type AssetType = 'stock' | 'crypto' | 'forex' | 'futures';

export function getAssetType(symbol: string): AssetType {
  if (symbol.endsWith('-USD') && CRYPTO_SYMBOLS.includes(symbol as typeof CRYPTO_SYMBOLS[number])) {
    return 'crypto';
  }
  if (symbol.endsWith('=X')) return 'forex';
  if (symbol.endsWith('=F')) return 'futures';
  return 'stock';
}

export const ASSET_INFO: Record<string, { name: string; category: string }> = {
  // Crypto
  'BTC-USD': { name: 'Bitcoin', category: 'Crypto' },
  'ETH-USD': { name: 'Ethereum', category: 'Crypto' },
  'BNB-USD': { name: 'Binance Coin', category: 'Crypto' },
  'XRP-USD': { name: 'Ripple', category: 'Crypto' },
  'SOL-USD': { name: 'Solana', category: 'Crypto' },
  'ADA-USD': { name: 'Cardano', category: 'Crypto' },
  'DOGE-USD': { name: 'Dogecoin', category: 'Crypto' },
  'AVAX-USD': { name: 'Avalanche', category: 'Crypto' },
  'DOT-USD': { name: 'Polkadot', category: 'Crypto' },
  'MATIC-USD': { name: 'Polygon', category: 'Crypto' },
  'LINK-USD': { name: 'Chainlink', category: 'Crypto' },
  'SHIB-USD': { name: 'Shiba Inu', category: 'Crypto' },
  'LTC-USD': { name: 'Litecoin', category: 'Crypto' },
  'ATOM-USD': { name: 'Cosmos', category: 'Crypto' },
  'UNI-USD': { name: 'Uniswap', category: 'Crypto' },
  'XLM-USD': { name: 'Stellar', category: 'Crypto' },
  'NEAR-USD': { name: 'NEAR Protocol', category: 'Crypto' },
  'APT-USD': { name: 'Aptos', category: 'Crypto' },
  'OP-USD': { name: 'Optimism', category: 'Crypto' },
  'ARB-USD': { name: 'Arbitrum', category: 'Crypto' },
  'FIL-USD': { name: 'Filecoin', category: 'Crypto' },
  'HBAR-USD': { name: 'Hedera', category: 'Crypto' },
  'ICP-USD': { name: 'Internet Computer', category: 'Crypto' },
  'VET-USD': { name: 'VeChain', category: 'Crypto' },
  'AAVE-USD': { name: 'Aave', category: 'Crypto' },
  'MKR-USD': { name: 'Maker', category: 'Crypto' },
  'GRT-USD': { name: 'The Graph', category: 'Crypto' },
  'INJ-USD': { name: 'Injective', category: 'Crypto' },
  'RUNE-USD': { name: 'THORChain', category: 'Crypto' },
  'FTM-USD': { name: 'Fantom', category: 'Crypto' },
  // DeFi & Layer 2
  'CRV-USD': { name: 'Curve DAO', category: 'Crypto' },
  'LDO-USD': { name: 'Lido DAO', category: 'Crypto' },
  'SNX-USD': { name: 'Synthetix', category: 'Crypto' },
  'COMP-USD': { name: 'Compound', category: 'Crypto' },
  'SUSHI-USD': { name: 'SushiSwap', category: 'Crypto' },
  'YFI-USD': { name: 'Yearn Finance', category: 'Crypto' },
  'BAL-USD': { name: 'Balancer', category: 'Crypto' },
  'UMA-USD': { name: 'UMA Protocol', category: 'Crypto' },
  '1INCH-USD': { name: '1inch Network', category: 'Crypto' },
  'DYDX-USD': { name: 'dYdX', category: 'Crypto' },
  'ENS-USD': { name: 'Ethereum Name Service', category: 'Crypto' },
  'RPL-USD': { name: 'Rocket Pool', category: 'Crypto' },
  'GMX-USD': { name: 'GMX', category: 'Crypto' },
  'JUP-USD': { name: 'Jupiter', category: 'Crypto' },
  'PENDLE-USD': { name: 'Pendle', category: 'Crypto' },
  'STRK-USD': { name: 'Starknet', category: 'Crypto' },
  // Infrastructure & Interoperability
  'ALGO-USD': { name: 'Algorand', category: 'Crypto' },
  'EGLD-USD': { name: 'MultiversX', category: 'Crypto' },
  'MINA-USD': { name: 'Mina Protocol', category: 'Crypto' },
  'FLOW-USD': { name: 'Flow', category: 'Crypto' },
  'KAVA-USD': { name: 'Kava', category: 'Crypto' },
  'ZEC-USD': { name: 'Zcash', category: 'Crypto' },
  'EOS-USD': { name: 'EOS', category: 'Crypto' },
  'XTZ-USD': { name: 'Tezos', category: 'Crypto' },
  'THETA-USD': { name: 'Theta Network', category: 'Crypto' },
  'AXS-USD': { name: 'Axie Infinity', category: 'Crypto' },
  'SAND-USD': { name: 'The Sandbox', category: 'Crypto' },
  'MANA-USD': { name: 'Decentraland', category: 'Crypto' },
  'ENJ-USD': { name: 'Enjin Coin', category: 'Crypto' },
  'CHZ-USD': { name: 'Chiliz', category: 'Crypto' },
  'GALA-USD': { name: 'Gala Games', category: 'Crypto' },
  'IMX-USD': { name: 'Immutable X', category: 'Crypto' },
  'RNDR-USD': { name: 'Render Token', category: 'Crypto' },
  'FET-USD': { name: 'Fetch.ai', category: 'Crypto' },
  // Meme & Trending
  'PEPE-USD': { name: 'Pepe', category: 'Crypto' },
  'WIF-USD': { name: 'Dogwifhat', category: 'Crypto' },
  'BONK-USD': { name: 'Bonk', category: 'Crypto' },
  'FLOKI-USD': { name: 'Floki Inu', category: 'Crypto' },
  // Layer 1 / New Chains
  'SUI-USD': { name: 'Sui', category: 'Crypto' },
  'SEI-USD': { name: 'Sei', category: 'Crypto' },
  'TIA-USD': { name: 'Celestia', category: 'Crypto' },
  'STX-USD': { name: 'Stacks', category: 'Crypto' },
  'KAS-USD': { name: 'Kaspa', category: 'Crypto' },
  'TON-USD': { name: 'Toncoin', category: 'Crypto' },
  'TRX-USD': { name: 'TRON', category: 'Crypto' },
  'BCH-USD': { name: 'Bitcoin Cash', category: 'Crypto' },
  'ETC-USD': { name: 'Ethereum Classic', category: 'Crypto' },
  'NEO-USD': { name: 'Neo', category: 'Crypto' },
  // AI & Data
  'TAO-USD': { name: 'Bittensor', category: 'Crypto' },
  'OCEAN-USD': { name: 'Ocean Protocol', category: 'Crypto' },
  'ONDO-USD': { name: 'Ondo Finance', category: 'Crypto' },
  'AGIX-USD': { name: 'SingularityNET', category: 'Crypto' },
  'WLD-USD': { name: 'Worldcoin', category: 'Crypto' },
  // Exchange & Utility
  'CRO-USD': { name: 'Cronos', category: 'Crypto' },
  'OKB-USD': { name: 'OKB', category: 'Crypto' },
  // Privacy & Legacy
  'XMR-USD': { name: 'Monero', category: 'Crypto' },
  'DASH-USD': { name: 'Dash', category: 'Crypto' },
  'ZIL-USD': { name: 'Zilliqa', category: 'Crypto' },
  'IOTA-USD': { name: 'IOTA', category: 'Crypto' },
  // Infrastructure
  'ANKR-USD': { name: 'Ankr', category: 'Crypto' },
  'STORJ-USD': { name: 'Storj', category: 'Crypto' },
  'BAT-USD': { name: 'Basic Attention Token', category: 'Crypto' },
  'CELO-USD': { name: 'Celo', category: 'Crypto' },
  'ROSE-USD': { name: 'Oasis Network', category: 'Crypto' },
  'ONE-USD': { name: 'Harmony', category: 'Crypto' },

  // Forex
  'EURUSD=X': { name: 'EUR/USD', category: 'Forex' },
  'GBPUSD=X': { name: 'GBP/USD', category: 'Forex' },
  'USDJPY=X': { name: 'USD/JPY', category: 'Forex' },
  'USDCHF=X': { name: 'USD/CHF', category: 'Forex' },
  'AUDUSD=X': { name: 'AUD/USD', category: 'Forex' },
  'USDCAD=X': { name: 'USD/CAD', category: 'Forex' },
  'NZDUSD=X': { name: 'NZD/USD', category: 'Forex' },
  'EURGBP=X': { name: 'EUR/GBP', category: 'Forex' },
  'EURJPY=X': { name: 'EUR/JPY', category: 'Forex' },
  'GBPJPY=X': { name: 'GBP/JPY', category: 'Forex' },
  'AUDJPY=X': { name: 'AUD/JPY', category: 'Forex' },
  'CADJPY=X': { name: 'CAD/JPY', category: 'Forex' },
  'EURAUD=X': { name: 'EUR/AUD', category: 'Forex' },
  'EURCHF=X': { name: 'EUR/CHF', category: 'Forex' },
  'GBPCHF=X': { name: 'GBP/CHF', category: 'Forex' },
  'USDMXN=X': { name: 'USD/MXN', category: 'Forex' },
  'USDZAR=X': { name: 'USD/ZAR', category: 'Forex' },
  'USDTRY=X': { name: 'USD/TRY', category: 'Forex' },
  'USDINR=X': { name: 'USD/INR', category: 'Forex' },
  'USDCNY=X': { name: 'USD/CNY', category: 'Forex' },
  'NZDJPY=X': { name: 'NZD/JPY', category: 'Forex' },
  'GBPAUD=X': { name: 'GBP/AUD', category: 'Forex' },
  'EURCZD=X': { name: 'EUR/CZK', category: 'Forex' },
  'AUDNZD=X': { name: 'AUD/NZD', category: 'Forex' },
  'GBPCAD=X': { name: 'GBP/CAD', category: 'Forex' },
  'AUDCAD=X': { name: 'AUD/CAD', category: 'Forex' },
  'CHFJPY=X': { name: 'CHF/JPY', category: 'Forex' },
  'EURNZD=X': { name: 'EUR/NZD', category: 'Forex' },
  'GBPNZD=X': { name: 'GBP/NZD', category: 'Forex' },
  'USDSGD=X': { name: 'USD/SGD', category: 'Forex' },
  'USDHKD=X': { name: 'USD/HKD', category: 'Forex' },
  'USDNOK=X': { name: 'USD/NOK', category: 'Forex' },
  'USDSEK=X': { name: 'USD/SEK', category: 'Forex' },
  'USDPLN=X': { name: 'USD/PLN', category: 'Forex' },
  'USDDKK=X': { name: 'USD/DKK', category: 'Forex' },
  'USDHUF=X': { name: 'USD/HUF', category: 'Forex' },
  'USDCZK=X': { name: 'USD/CZK', category: 'Forex' },
  'USDTHB=X': { name: 'USD/THB', category: 'Forex' },
  'USDIDR=X': { name: 'USD/IDR', category: 'Forex' },
  'USDTWD=X': { name: 'USD/TWD', category: 'Forex' },
  'USDKRW=X': { name: 'USD/KRW', category: 'Forex' },
  'USDBRL=X': { name: 'USD/BRL', category: 'Forex' },
  'USDCLP=X': { name: 'USD/CLP', category: 'Forex' },
  'USDCOP=X': { name: 'USD/COP', category: 'Forex' },

  // Futures
  'ES=F': { name: 'S&P 500 E-mini', category: 'Futures' },
  'NQ=F': { name: 'NASDAQ-100 E-mini', category: 'Futures' },
  'YM=F': { name: 'Dow Jones Mini', category: 'Futures' },
  'RTY=F': { name: 'Russell 2000 E-mini', category: 'Futures' },
  'GC=F': { name: 'Gold', category: 'Futures' },
  'SI=F': { name: 'Silver', category: 'Futures' },
  'CL=F': { name: 'Crude Oil WTI', category: 'Futures' },
  'BZ=F': { name: 'Brent Crude Oil', category: 'Futures' },
  'NG=F': { name: 'Natural Gas', category: 'Futures' },
  'HG=F': { name: 'Copper', category: 'Futures' },
  'PL=F': { name: 'Platinum', category: 'Futures' },
  'ZC=F': { name: 'Corn', category: 'Futures' },
  'ZW=F': { name: 'Wheat', category: 'Futures' },
  'ZS=F': { name: 'Soybeans', category: 'Futures' },
  'ZB=F': { name: 'Treasury Bond 30Y', category: 'Futures' },
  'ZN=F': { name: 'Treasury Note 10Y', category: 'Futures' },
  '6E=F': { name: 'Euro FX', category: 'Futures' },
  '6B=F': { name: 'British Pound', category: 'Futures' },
  '6J=F': { name: 'Japanese Yen', category: 'Futures' },
  'VIX=F': { name: 'CBOE Volatility Index', category: 'Futures' },
  'NIKKEI=F': { name: 'Nikkei 225', category: 'Futures' },
  'HO=F': { name: 'Heating Oil', category: 'Futures' },
  'RB=F': { name: 'RBOB Gasoline', category: 'Futures' },
  'PA=F': { name: 'Palladium', category: 'Futures' },
  'ZM=F': { name: 'Soybean Meal', category: 'Futures' },
  'ZL=F': { name: 'Soybean Oil', category: 'Futures' },
  'CT=F': { name: 'Cotton', category: 'Futures' },
  'KC=F': { name: 'Coffee', category: 'Futures' },
  'SB=F': { name: 'Sugar', category: 'Futures' },
  'CC=F': { name: 'Cocoa', category: 'Futures' },
  'OJ=F': { name: 'Orange Juice', category: 'Futures' },
  'LC=F': { name: 'Live Cattle', category: 'Futures' },
  'LH=F': { name: 'Lean Hogs', category: 'Futures' },
  'FC=F': { name: 'Feeder Cattle', category: 'Futures' },
  'ZF=F': { name: 'Treasury Note 5Y', category: 'Futures' },
  'ZT=F': { name: 'Treasury Note 2Y', category: 'Futures' },
  '6A=F': { name: 'Australian Dollar', category: 'Futures' },
  '6C=F': { name: 'Canadian Dollar', category: 'Futures' },
  '6S=F': { name: 'Swiss Franc', category: 'Futures' },
  '6N=F': { name: 'New Zealand Dollar', category: 'Futures' },
  '6M=F': { name: 'Mexican Peso', category: 'Futures' },
  'ZO=F': { name: 'Oats', category: 'Futures' },
  'ZR=F': { name: 'Rough Rice', category: 'Futures' },
  'LBS=F': { name: 'Lumber', category: 'Futures' },
  'DX=F': { name: 'U.S. Dollar Index', category: 'Futures' },
  'BTC=F': { name: 'CME Bitcoin', category: 'Futures' },
  'ETH=F': { name: 'CME Ethereum', category: 'Futures' },

  // Mega Cap Tech Stocks
  NVDA: { name: 'NVIDIA Corporation', category: 'Technology' },
  AAPL: { name: 'Apple Inc.', category: 'Technology' },
  MSFT: { name: 'Microsoft Corporation', category: 'Technology' },
  AMZN: { name: 'Amazon.com Inc.', category: 'Consumer Cyclical' },
  GOOGL: { name: 'Alphabet Inc. Class A', category: 'Technology' },
  GOOG: { name: 'Alphabet Inc. Class C', category: 'Technology' },
  META: { name: 'Meta Platforms Inc.', category: 'Technology' },
  AVGO: { name: 'Broadcom Inc.', category: 'Technology' },
  TSLA: { name: 'Tesla Inc.', category: 'Consumer Cyclical' },

  // Financials
  'BRK-B': { name: 'Berkshire Hathaway Class B', category: 'Financial' },
  JPM: { name: 'JPMorgan Chase & Co.', category: 'Financial' },
  V: { name: 'Visa Inc.', category: 'Financial' },
  MA: { name: 'Mastercard Inc.', category: 'Financial' },
  BAC: { name: 'Bank of America Corp.', category: 'Financial' },
  WFC: { name: 'Wells Fargo & Co.', category: 'Financial' },
  GS: { name: 'Goldman Sachs Group', category: 'Financial' },
  MS: { name: 'Morgan Stanley', category: 'Financial' },
  BLK: { name: 'BlackRock Inc.', category: 'Financial' },
  AXP: { name: 'American Express Co.', category: 'Financial' },
  C: { name: 'Citigroup Inc.', category: 'Financial' },
  SCHW: { name: 'Charles Schwab Corp.', category: 'Financial' },
  COF: { name: 'Capital One Financial', category: 'Financial' },
  COIN: { name: 'Coinbase Global', category: 'Financial' },
  HOOD: { name: 'Robinhood Markets', category: 'Financial' },
  PYPL: { name: 'PayPal Holdings', category: 'Financial' },

  // Healthcare
  LLY: { name: 'Eli Lilly and Co.', category: 'Healthcare' },
  UNH: { name: 'UnitedHealth Group', category: 'Healthcare' },
  JNJ: { name: 'Johnson & Johnson', category: 'Healthcare' },
  PFE: { name: 'Pfizer Inc.', category: 'Healthcare' },
  ABBV: { name: 'AbbVie Inc.', category: 'Healthcare' },
  MRK: { name: 'Merck & Co. Inc.', category: 'Healthcare' },
  TMO: { name: 'Thermo Fisher Scientific', category: 'Healthcare' },
  ABT: { name: 'Abbott Laboratories', category: 'Healthcare' },
  DHR: { name: 'Danaher Corporation', category: 'Healthcare' },
  BMY: { name: 'Bristol-Myers Squibb', category: 'Healthcare' },
  ISRG: { name: 'Intuitive Surgical', category: 'Healthcare' },
  AMGN: { name: 'Amgen Inc.', category: 'Healthcare' },
  GILD: { name: 'Gilead Sciences', category: 'Healthcare' },
  VRTX: { name: 'Vertex Pharmaceuticals', category: 'Healthcare' },
  REGN: { name: 'Regeneron Pharmaceuticals', category: 'Healthcare' },

  // Consumer
  WMT: { name: 'Walmart Inc.', category: 'Consumer Defensive' },
  PG: { name: 'Procter & Gamble Co.', category: 'Consumer Defensive' },
  KO: { name: 'Coca-Cola Company', category: 'Consumer Defensive' },
  PEP: { name: 'PepsiCo Inc.', category: 'Consumer Defensive' },
  COST: { name: 'Costco Wholesale Corp.', category: 'Consumer Defensive' },
  HD: { name: 'Home Depot Inc.', category: 'Consumer Cyclical' },
  MCD: { name: "McDonald's Corporation", category: 'Consumer Cyclical' },
  NKE: { name: 'Nike Inc.', category: 'Consumer Cyclical' },
  SBUX: { name: 'Starbucks Corporation', category: 'Consumer Cyclical' },
  TGT: { name: 'Target Corporation', category: 'Consumer Defensive' },
  LOW: { name: "Lowe's Companies", category: 'Consumer Cyclical' },
  TJX: { name: 'TJX Companies', category: 'Consumer Cyclical' },

  // Energy
  XOM: { name: 'Exxon Mobil Corporation', category: 'Energy' },
  CVX: { name: 'Chevron Corporation', category: 'Energy' },
  COP: { name: 'ConocoPhillips', category: 'Energy' },
  SLB: { name: 'Schlumberger Limited', category: 'Energy' },
  EOG: { name: 'EOG Resources', category: 'Energy' },
  OXY: { name: 'Occidental Petroleum', category: 'Energy' },

  // Industrial
  CAT: { name: 'Caterpillar Inc.', category: 'Industrial' },
  BA: { name: 'Boeing Company', category: 'Industrial' },
  UNP: { name: 'Union Pacific Corp.', category: 'Industrial' },
  HON: { name: 'Honeywell International', category: 'Industrial' },
  GE: { name: 'General Electric Co.', category: 'Industrial' },
  RTX: { name: 'RTX Corporation', category: 'Industrial' },
  LMT: { name: 'Lockheed Martin Corp.', category: 'Industrial' },
  DE: { name: 'Deere & Company', category: 'Industrial' },

  // More Tech
  ORCL: { name: 'Oracle Corporation', category: 'Technology' },
  CRM: { name: 'Salesforce Inc.', category: 'Technology' },
  CSCO: { name: 'Cisco Systems', category: 'Technology' },
  IBM: { name: 'IBM Corporation', category: 'Technology' },
  INTC: { name: 'Intel Corporation', category: 'Technology' },
  AMD: { name: 'Advanced Micro Devices', category: 'Technology' },
  QCOM: { name: 'Qualcomm Inc.', category: 'Technology' },
  TXN: { name: 'Texas Instruments', category: 'Technology' },
  ADBE: { name: 'Adobe Inc.', category: 'Technology' },
  NOW: { name: 'ServiceNow Inc.', category: 'Technology' },
  INTU: { name: 'Intuit Inc.', category: 'Technology' },
  MU: { name: 'Micron Technology', category: 'Technology' },
  AMAT: { name: 'Applied Materials', category: 'Technology' },
  LRCX: { name: 'Lam Research', category: 'Technology' },
  KLAC: { name: 'KLA Corporation', category: 'Technology' },
  ADI: { name: 'Analog Devices', category: 'Technology' },
  SNPS: { name: 'Synopsys Inc.', category: 'Technology' },
  CDNS: { name: 'Cadence Design Systems', category: 'Technology' },
  NFLX: { name: 'Netflix Inc.', category: 'Communication Services' },
  PLTR: { name: 'Palantir Technologies', category: 'Technology' },
  PANW: { name: 'Palo Alto Networks', category: 'Technology' },
  CRWD: { name: 'CrowdStrike Holdings', category: 'Technology' },

  // Communication Services
  T: { name: 'AT&T Inc.', category: 'Communication Services' },
  VZ: { name: 'Verizon Communications', category: 'Communication Services' },
  TMUS: { name: 'T-Mobile US', category: 'Communication Services' },
  DIS: { name: 'Walt Disney Company', category: 'Communication Services' },
  CMCSA: { name: 'Comcast Corporation', category: 'Communication Services' },

  // Utilities
  NEE: { name: 'NextEra Energy', category: 'Utilities' },
  DUK: { name: 'Duke Energy Corp.', category: 'Utilities' },
  SO: { name: 'Southern Company', category: 'Utilities' },

  // Real Estate
  PLD: { name: 'Prologis Inc.', category: 'Real Estate' },
  AMT: { name: 'American Tower Corp.', category: 'Real Estate' },
  EQIX: { name: 'Equinix Inc.', category: 'Real Estate' },

  // Other notable stocks
  UBER: { name: 'Uber Technologies', category: 'Technology' },
  ABNB: { name: 'Airbnb Inc.', category: 'Consumer Cyclical' },
  DASH: { name: 'DoorDash Inc.', category: 'Consumer Cyclical' },
  GM: { name: 'General Motors', category: 'Consumer Cyclical' },
  F: { name: 'Ford Motor Company', category: 'Consumer Cyclical' },
  CVS: { name: 'CVS Health Corp.', category: 'Healthcare' },

  // NASDAQ Additional - Growth Stocks
  MELI: { name: 'MercadoLibre', category: 'Consumer Cyclical' },
  TEAM: { name: 'Atlassian', category: 'Technology' },
  LCID: { name: 'Lucid Group', category: 'Consumer Cyclical' },
  RIVN: { name: 'Rivian Automotive', category: 'Consumer Cyclical' },
  OKTA: { name: 'Okta Inc.', category: 'Technology' },
  ZM: { name: 'Zoom Video Communications', category: 'Technology' },
  DOCU: { name: 'DocuSign Inc.', category: 'Technology' },
  ROKU: { name: 'Roku Inc.', category: 'Communication Services' },
  NET: { name: 'Cloudflare Inc.', category: 'Technology' },
  CRSP: { name: 'CRISPR Therapeutics', category: 'Healthcare' },
  ILMN: { name: 'Illumina Inc.', category: 'Healthcare' },
  ASML: { name: 'ASML Holding', category: 'Technology' },
  MRVL: { name: 'Marvell Technology', category: 'Technology' },
  PDD: { name: 'PDD Holdings', category: 'Consumer Cyclical' },
  JD: { name: 'JD.com', category: 'Consumer Cyclical' },
  BIDU: { name: 'Baidu Inc.', category: 'Technology' },
  NTES: { name: 'NetEase Inc.', category: 'Technology' },
  TCOM: { name: 'Trip.com Group', category: 'Consumer Cyclical' },

  // NASDAQ Growth & Fintech
  SOFI: { name: 'SoFi Technologies', category: 'Financial' },
  UPST: { name: 'Upstart Holdings', category: 'Financial' },
  AFRM: { name: 'Affirm Holdings', category: 'Financial' },
  PATH: { name: 'UiPath', category: 'Technology' },
  SNOW: { name: 'Snowflake Inc.', category: 'Technology' },
  DKNG: { name: 'DraftKings', category: 'Consumer Cyclical' },
  RBLX: { name: 'Roblox Corporation', category: 'Technology' },
  U: { name: 'Unity Software', category: 'Technology' },
  BILL: { name: 'Bill.com Holdings', category: 'Technology' },
  HUBS: { name: 'HubSpot Inc.', category: 'Technology' },
  TWLO: { name: 'Twilio Inc.', category: 'Technology' },
  MDB: { name: 'MongoDB Inc.', category: 'Technology' },
  CFLT: { name: 'Confluent Inc.', category: 'Technology' },
  GTLB: { name: 'GitLab Inc.', category: 'Technology' },
  S: { name: 'SentinelOne', category: 'Technology' },
  DUOL: { name: 'Duolingo Inc.', category: 'Technology' },
  PINS: { name: 'Pinterest Inc.', category: 'Technology' },
  SNAP: { name: 'Snap Inc.', category: 'Technology' },
  SPOT: { name: 'Spotify Technology', category: 'Communication Services' },
  LYFT: { name: 'Lyft Inc.', category: 'Technology' },
  GRAB: { name: 'Grab Holdings', category: 'Technology' },
  SE: { name: 'Sea Limited', category: 'Consumer Cyclical' },
  SHOP: { name: 'Shopify Inc.', category: 'Technology' },
  SQ: { name: 'Block Inc.', category: 'Financial' },
  FUBO: { name: 'fuboTV Inc.', category: 'Communication Services' },

  // NASDAQ Biotech
  MRNA: { name: 'Moderna Inc.', category: 'Healthcare' },
  BNTX: { name: 'BioNTech SE', category: 'Healthcare' },
  NVAX: { name: 'Novavax Inc.', category: 'Healthcare' },
  SGEN: { name: 'Seagen Inc.', category: 'Healthcare' },
  EXAS: { name: 'Exact Sciences', category: 'Healthcare' },
  ALNY: { name: 'Alnylam Pharmaceuticals', category: 'Healthcare' },
  SRPT: { name: 'Sarepta Therapeutics', category: 'Healthcare' },
  RARE: { name: 'Ultragenyx Pharmaceutical', category: 'Healthcare' },
  BMRN: { name: 'BioMarin Pharmaceutical', category: 'Healthcare' },
  NBIX: { name: 'Neurocrine Biosciences', category: 'Healthcare' },
  UTHR: { name: 'United Therapeutics', category: 'Healthcare' },
  INCY: { name: 'Incyte Corporation', category: 'Healthcare' },
  IONS: { name: 'Ionis Pharmaceuticals', category: 'Healthcare' },
  HALO: { name: 'Halozyme Therapeutics', category: 'Healthcare' },
  LEGN: { name: 'Legend Biotech', category: 'Healthcare' },
  PCVX: { name: 'Vaxcyte Inc.', category: 'Healthcare' },
  KRYS: { name: 'Krystal Biotech', category: 'Healthcare' },

  // NASDAQ Tech & AI
  ARM: { name: 'ARM Holdings', category: 'Technology' },
  SMCI: { name: 'Super Micro Computer', category: 'Technology' },
  IONQ: { name: 'IonQ Inc.', category: 'Technology' },
  RGTI: { name: 'Rigetti Computing', category: 'Technology' },
  AI: { name: 'C3.ai Inc.', category: 'Technology' },
  SOUN: { name: 'SoundHound AI', category: 'Technology' },
  BBAI: { name: 'BigBear.ai Holdings', category: 'Technology' },
  UPWK: { name: 'Upwork Inc.', category: 'Technology' },
  FVRR: { name: 'Fiverr International', category: 'Technology' },
  WIX: { name: 'Wix.com Ltd.', category: 'Technology' },
  ZI: { name: 'ZoomInfo Technologies', category: 'Technology' },
  ESTC: { name: 'Elastic N.V.', category: 'Technology' },
  NEWR: { name: 'New Relic Inc.', category: 'Technology' },
  ASAN: { name: 'Asana Inc.', category: 'Technology' },
  MNDY: { name: 'Monday.com Ltd.', category: 'Technology' },
  DOCN: { name: 'DigitalOcean Holdings', category: 'Technology' },
  FSLY: { name: 'Fastly Inc.', category: 'Technology' },
  AKAM: { name: 'Akamai Technologies', category: 'Technology' },

  // NASDAQ Consumer & Retail
  LULU: { name: 'Lululemon Athletica', category: 'Consumer Cyclical' },
  ROST: { name: 'Ross Stores', category: 'Consumer Cyclical' },
  DLTR: { name: 'Dollar Tree Inc.', category: 'Consumer Defensive' },
  DG: { name: 'Dollar General', category: 'Consumer Defensive' },
  FIVE: { name: 'Five Below Inc.', category: 'Consumer Cyclical' },
  OLLI: { name: "Ollie's Bargain Outlet", category: 'Consumer Cyclical' },
  TSCO: { name: 'Tractor Supply Co.', category: 'Consumer Cyclical' },
  WSM: { name: 'Williams-Sonoma', category: 'Consumer Cyclical' },
  RH: { name: 'Restoration Hardware', category: 'Consumer Cyclical' },
  ETSY: { name: 'Etsy Inc.', category: 'Consumer Cyclical' },
  W: { name: 'Wayfair Inc.', category: 'Consumer Cyclical' },
  CHWY: { name: 'Chewy Inc.', category: 'Consumer Cyclical' },
  CVNA: { name: 'Carvana Co.', category: 'Consumer Cyclical' },
  CPNG: { name: 'Coupang Inc.', category: 'Consumer Cyclical' },
  BABA: { name: 'Alibaba Group', category: 'Consumer Cyclical' },

  // NASDAQ EV & Clean Energy
  NIO: { name: 'NIO Inc.', category: 'Consumer Cyclical' },
  XPEV: { name: 'XPeng Inc.', category: 'Consumer Cyclical' },
  LI: { name: 'Li Auto Inc.', category: 'Consumer Cyclical' },
  FSR: { name: 'Fisker Inc.', category: 'Consumer Cyclical' },
  GOEV: { name: 'Canoo Inc.', category: 'Consumer Cyclical' },
  WKHS: { name: 'Workhorse Group', category: 'Industrial' },
  HYLN: { name: 'Hyliion Holdings', category: 'Industrial' },
  CHPT: { name: 'ChargePoint Holdings', category: 'Industrial' },
  BLNK: { name: 'Blink Charging', category: 'Industrial' },
  EVGO: { name: 'EVgo Inc.', category: 'Industrial' },
  QS: { name: 'QuantumScape Corp.', category: 'Technology' },
  PLUG: { name: 'Plug Power Inc.', category: 'Industrial' },
  FCEL: { name: 'FuelCell Energy', category: 'Industrial' },
  BE: { name: 'Bloom Energy Corp.', category: 'Industrial' },
  SEDG: { name: 'SolarEdge Technologies', category: 'Technology' },
  RUN: { name: 'Sunrun Inc.', category: 'Industrial' },

  // NASDAQ Media & Entertainment
  PARA: { name: 'Paramount Global', category: 'Communication Services' },
  WBD: { name: 'Warner Bros Discovery', category: 'Communication Services' },
  LYV: { name: 'Live Nation Entertainment', category: 'Communication Services' },
  MTCH: { name: 'Match Group', category: 'Communication Services' },
  BMBL: { name: 'Bumble Inc.', category: 'Communication Services' },
  TTWO: { name: 'Take-Two Interactive', category: 'Communication Services' },
  EA: { name: 'Electronic Arts', category: 'Communication Services' },

  // NASDAQ Communications
  LUMN: { name: 'Lumen Technologies', category: 'Communication Services' },
  FYBR: { name: 'Frontier Communications', category: 'Communication Services' },
  USM: { name: 'United States Cellular', category: 'Communication Services' },
  SATS: { name: 'EchoStar Corporation', category: 'Communication Services' },
  GSAT: { name: 'Globalstar Inc.', category: 'Communication Services' },
  IRDM: { name: 'Iridium Communications', category: 'Communication Services' },

  // NASDAQ Transportation
  ODFL: { name: 'Old Dominion Freight', category: 'Industrial' },
  SAIA: { name: 'Saia Inc.', category: 'Industrial' },
  XPO: { name: 'XPO Logistics', category: 'Industrial' },
  JBHT: { name: 'J.B. Hunt Transport', category: 'Industrial' },
  CHRW: { name: 'C.H. Robinson', category: 'Industrial' },
  EXPD: { name: 'Expeditors International', category: 'Industrial' },
  LSTR: { name: 'Landstar System', category: 'Industrial' },
  WERN: { name: 'Werner Enterprises', category: 'Industrial' },
  KNX: { name: 'Knight-Swift Transportation', category: 'Industrial' },
  SNDR: { name: 'Schneider National', category: 'Industrial' },

  // NASDAQ REITs
  DLR: { name: 'Digital Realty Trust', category: 'Real Estate' },
  SBAC: { name: 'SBA Communications', category: 'Real Estate' },
  CCI: { name: 'Crown Castle', category: 'Real Estate' },
  REXR: { name: 'Rexford Industrial', category: 'Real Estate' },
  COLD: { name: 'Americold Realty', category: 'Real Estate' },
  IIPR: { name: 'Innovative Industrial Properties', category: 'Real Estate' },

  // NASDAQ Financial
  MSTR: { name: 'MicroStrategy', category: 'Technology' },
  IBKR: { name: 'Interactive Brokers', category: 'Financial' },
  VIRT: { name: 'Virtu Financial', category: 'Financial' },
  NDAQ: { name: 'Nasdaq Inc.', category: 'Financial' },
  LPLA: { name: 'LPL Financial', category: 'Financial' },

  // Additional NASDAQ Biotech
  NTLA: { name: 'Intellia Therapeutics', category: 'Healthcare' },
  EDIT: { name: 'Editas Medicine', category: 'Healthcare' },
  BEAM: { name: 'Beam Therapeutics', category: 'Healthcare' },
  ARWR: { name: 'Arrowhead Research', category: 'Healthcare' },
  BGNE: { name: 'BeiGene Ltd.', category: 'Healthcare' },
  JAZZ: { name: 'Jazz Pharmaceuticals', category: 'Healthcare' },
  EXEL: { name: 'Exelixis Inc.', category: 'Healthcare' },
  IOVA: { name: 'Iovance Biotherapeutics', category: 'Healthcare' },
  SAGE: { name: 'Sage Therapeutics', category: 'Healthcare' },
  ACAD: { name: 'Acadia Pharmaceuticals', category: 'Healthcare' },

  // Additional Tech & SaaS
  SPLK: { name: 'Splunk Inc.', category: 'Technology' },
  DBX: { name: 'Dropbox Inc.', category: 'Technology' },
  BOX: { name: 'Box Inc.', category: 'Technology' },
  COUP: { name: 'Coupa Software', category: 'Technology' },
  QLYS: { name: 'Qualys Inc.', category: 'Technology' },
  TENB: { name: 'Tenable Holdings', category: 'Technology' },
  VRNS: { name: 'Varonis Systems', category: 'Technology' },
  RPD: { name: 'Rapid7 Inc.', category: 'Technology' },
  NTNX: { name: 'Nutanix Inc.', category: 'Technology' },
  MANH: { name: 'Manhattan Associates', category: 'Technology' },
  PEGA: { name: 'Pegasystems Inc.', category: 'Technology' },
  PLAN: { name: 'Anaplan Inc.', category: 'Technology' },
  TOST: { name: 'Toast Inc.', category: 'Technology' },
  BRZE: { name: 'Braze Inc.', category: 'Technology' },
  JAMF: { name: 'Jamf Holding', category: 'Technology' },

  // Additional Semiconductors
  WOLF: { name: 'Wolfspeed Inc.', category: 'Technology' },
  CRUS: { name: 'Cirrus Logic', category: 'Technology' },
  DIOD: { name: 'Diodes Inc.', category: 'Technology' },
  MKSI: { name: 'MKS Instruments', category: 'Technology' },
  OLED: { name: 'Universal Display', category: 'Technology' },
  ONTO: { name: 'Onto Innovation', category: 'Technology' },
  POWI: { name: 'Power Integrations', category: 'Technology' },
  QRVO: { name: 'Qorvo Inc.', category: 'Technology' },
  RMBS: { name: 'Rambus Inc.', category: 'Technology' },
  SLAB: { name: 'Silicon Labs', category: 'Technology' },

  // Additional EV & Clean Tech
  ARRY: { name: 'Array Technologies', category: 'Industrial' },
  BLDP: { name: 'Ballard Power', category: 'Industrial' },
  GEVO: { name: 'Gevo Inc.', category: 'Industrial' },
  STEM: { name: 'Stem Inc.', category: 'Technology' },
  LAZR: { name: 'Luminar Technologies', category: 'Technology' },
  NKLA: { name: 'Nikola Corporation', category: 'Consumer Cyclical' },

  // Additional Consumer
  ONON: { name: 'On Holding AG', category: 'Consumer Cyclical' },
  PTON: { name: 'Peloton Interactive', category: 'Consumer Cyclical' },
  SHAK: { name: 'Shake Shack', category: 'Consumer Cyclical' },
  WING: { name: 'Wingstop Inc.', category: 'Consumer Cyclical' },
  TXRH: { name: 'Texas Roadhouse', category: 'Consumer Cyclical' },
  ELF: { name: 'e.l.f. Beauty', category: 'Consumer Cyclical' },
  CROX: { name: 'Crocs Inc.', category: 'Consumer Cyclical' },
  YETI: { name: 'YETI Holdings', category: 'Consumer Cyclical' },
  BROS: { name: 'Dutch Bros Inc.', category: 'Consumer Cyclical' },

  // Additional Fintech
  LMND: { name: 'Lemonade Inc.', category: 'Financial' },
  RKT: { name: 'Rocket Companies', category: 'Financial' },
  LC: { name: 'LendingClub Corp', category: 'Financial' },
  ALLY: { name: 'Ally Financial', category: 'Financial' },
  FCNCA: { name: 'First Citizens Bank', category: 'Financial' },
  WAL: { name: 'Western Alliance', category: 'Financial' },

  // Additional Media & Gaming
  MARA: { name: 'Marathon Digital', category: 'Technology' },
  RIOT: { name: 'Riot Platforms', category: 'Technology' },
  WMG: { name: 'Warner Music Group', category: 'Communication Services' },
  SONO: { name: 'Sonos Inc.', category: 'Technology' },
  IMAX: { name: 'IMAX Corporation', category: 'Communication Services' },

  // Additional Industrial
  ZBRA: { name: 'Zebra Technologies', category: 'Technology' },
  LOGI: { name: 'Logitech International', category: 'Technology' },
  IRBT: { name: 'iRobot Corporation', category: 'Consumer Cyclical' },
  GNRC: { name: 'Generac Holdings', category: 'Industrial' },
  AVAV: { name: 'AeroVironment Inc.', category: 'Industrial' },
  KTOS: { name: 'Kratos Defense', category: 'Industrial' },

  // Additional S&P 500 / NASDAQ stocks
  CINF: { name: 'Cincinnati Financial', category: 'Financial' },
  CHTR: { name: 'Charter Communications', category: 'Communication Services' },
  CF: { name: 'CF Industries Holdings', category: 'Materials' },
  CFG: { name: 'Citizens Financial Group', category: 'Financial' },
  CHD: { name: 'Church & Dwight Co.', category: 'Consumer Defensive' },
  CI: { name: 'The Cigna Group', category: 'Healthcare' },
  CL: { name: 'Colgate-Palmolive Co.', category: 'Consumer Defensive' },
  CLX: { name: 'Clorox Company', category: 'Consumer Defensive' },
  CMA: { name: 'Comerica Inc.', category: 'Financial' },
  CME: { name: 'CME Group Inc.', category: 'Financial' },
  CMG: { name: 'Chipotle Mexican Grill', category: 'Consumer Cyclical' },
  CMI: { name: 'Cummins Inc.', category: 'Industrial' },
  CMS: { name: 'CMS Energy Corp.', category: 'Utilities' },
  CNC: { name: 'Centene Corporation', category: 'Healthcare' },
  CNP: { name: 'CenterPoint Energy', category: 'Utilities' },
  CPRT: { name: 'Copart Inc.', category: 'Industrial' },
  CRL: { name: 'Charles River Laboratories', category: 'Healthcare' },
  CSGP: { name: 'CoStar Group Inc.', category: 'Real Estate' },
  CSX: { name: 'CSX Corporation', category: 'Industrial' },
  CTAS: { name: 'Cintas Corporation', category: 'Industrial' },
  CTLT: { name: 'Catalent Inc.', category: 'Healthcare' },
  CTRA: { name: 'Coterra Energy Inc.', category: 'Energy' },
  CTSH: { name: 'Cognizant Technology', category: 'Technology' },
  CTVA: { name: 'Corteva Inc.', category: 'Materials' },
  CZR: { name: 'Caesars Entertainment', category: 'Consumer Cyclical' },
  D: { name: 'Dominion Energy Inc.', category: 'Utilities' },
  DAL: { name: 'Delta Air Lines Inc.', category: 'Industrial' },
  DD: { name: 'DuPont de Nemours', category: 'Materials' },
  DFS: { name: 'Discover Financial', category: 'Financial' },
  DGX: { name: 'Quest Diagnostics Inc.', category: 'Healthcare' },
  DHI: { name: 'D.R. Horton Inc.', category: 'Consumer Cyclical' },
  DOV: { name: 'Dover Corporation', category: 'Industrial' },
  DOW: { name: 'Dow Inc.', category: 'Materials' },
  DPZ: { name: "Domino's Pizza Inc.", category: 'Consumer Cyclical' },
  DRI: { name: 'Darden Restaurants', category: 'Consumer Cyclical' },
  DTE: { name: 'DTE Energy Company', category: 'Utilities' },
  DVA: { name: 'DaVita Inc.', category: 'Healthcare' },
  DVN: { name: 'Devon Energy Corp.', category: 'Energy' },
  DXCM: { name: 'DexCom Inc.', category: 'Healthcare' },
  EBAY: { name: 'eBay Inc.', category: 'Consumer Cyclical' },
  ECL: { name: 'Ecolab Inc.', category: 'Materials' },
  ED: { name: 'Consolidated Edison', category: 'Utilities' },
  EFX: { name: 'Equifax Inc.', category: 'Industrial' },
  EG: { name: 'Everest Group Ltd.', category: 'Financial' },
  EIX: { name: 'Edison International', category: 'Utilities' },
  EL: { name: 'Estée Lauder Companies', category: 'Consumer Defensive' },
  EMN: { name: 'Eastman Chemical Co.', category: 'Materials' },
  EMR: { name: 'Emerson Electric Co.', category: 'Industrial' },
  ENPH: { name: 'Enphase Energy Inc.', category: 'Technology' },
  EPAM: { name: 'EPAM Systems Inc.', category: 'Technology' },
  EQR: { name: 'Equity Residential', category: 'Real Estate' },
  EQT: { name: 'EQT Corporation', category: 'Energy' },
  ES: { name: 'Eversource Energy', category: 'Utilities' },
  ESS: { name: 'Essex Property Trust', category: 'Real Estate' },
  ETN: { name: 'Eaton Corporation', category: 'Industrial' },
  ETR: { name: 'Entergy Corporation', category: 'Utilities' },
  EVRG: { name: 'Evergy Inc.', category: 'Utilities' },
  EW: { name: 'Edwards Lifesciences', category: 'Healthcare' },
  EXC: { name: 'Exelon Corporation', category: 'Utilities' },
  EXPE: { name: 'Expedia Group Inc.', category: 'Consumer Cyclical' },
  EXR: { name: 'Extra Space Storage', category: 'Real Estate' },
  FANG: { name: 'Diamondback Energy', category: 'Energy' },
  FAST: { name: 'Fastenal Company', category: 'Industrial' },
  FCX: { name: 'Freeport-McMoRan Inc.', category: 'Materials' },
  FDS: { name: 'FactSet Research Systems', category: 'Financial' },
  FDX: { name: 'FedEx Corporation', category: 'Industrial' },
  FE: { name: 'FirstEnergy Corp.', category: 'Utilities' },
  FFIV: { name: 'F5 Inc.', category: 'Technology' },
  FIS: { name: 'Fidelity National Info', category: 'Technology' },
  FISV: { name: 'Fiserv Inc.', category: 'Technology' },
  FITB: { name: 'Fifth Third Bancorp', category: 'Financial' },
  FLT: { name: 'Fleetcor Technologies', category: 'Technology' },
  FMC: { name: 'FMC Corporation', category: 'Materials' },
  FOX: { name: 'Fox Corporation Class B', category: 'Communication Services' },
  FOXA: { name: 'Fox Corporation Class A', category: 'Communication Services' },
  FRC: { name: 'First Republic Bank', category: 'Financial' },
  FRT: { name: 'Federal Realty Trust', category: 'Real Estate' },
  FTNT: { name: 'Fortinet Inc.', category: 'Technology' },
  FTV: { name: 'Fortive Corporation', category: 'Industrial' },
  GD: { name: 'General Dynamics Corp.', category: 'Industrial' },
  GEN: { name: 'Gen Digital Inc.', category: 'Technology' },
  GIS: { name: 'General Mills Inc.', category: 'Consumer Defensive' },
  GL: { name: 'Globe Life Inc.', category: 'Financial' },
  GLW: { name: 'Corning Inc.', category: 'Technology' },
  GRMN: { name: 'Garmin Ltd.', category: 'Technology' },
  GWW: { name: 'W.W. Grainger Inc.', category: 'Industrial' },
  HAL: { name: 'Halliburton Company', category: 'Energy' },
  HAS: { name: 'Hasbro Inc.', category: 'Consumer Cyclical' },
  HBAN: { name: 'Huntington Bancshares', category: 'Financial' },
  HCA: { name: 'HCA Healthcare Inc.', category: 'Healthcare' },
  HES: { name: 'Hess Corporation', category: 'Energy' },
  HIG: { name: 'Hartford Financial', category: 'Financial' },
  HII: { name: 'Huntington Ingalls', category: 'Industrial' },
  HLT: { name: 'Hilton Worldwide', category: 'Consumer Cyclical' },
  HOLX: { name: 'Hologic Inc.', category: 'Healthcare' },
  HPE: { name: 'Hewlett Packard Enterprise', category: 'Technology' },
  HPQ: { name: 'HP Inc.', category: 'Technology' },
  HRL: { name: 'Hormel Foods Corp.', category: 'Consumer Defensive' },
  HSIC: { name: 'Henry Schein Inc.', category: 'Healthcare' },
  HST: { name: 'Host Hotels & Resorts', category: 'Real Estate' },
  HSY: { name: 'Hershey Company', category: 'Consumer Defensive' },
  HUBB: { name: 'Hubbell Inc.', category: 'Industrial' },
  HUM: { name: 'Humana Inc.', category: 'Healthcare' },
  HWM: { name: 'Howmet Aerospace Inc.', category: 'Industrial' },
  ICE: { name: 'Intercontinental Exchange', category: 'Financial' },
  IDXX: { name: 'IDEXX Laboratories', category: 'Healthcare' },
  IEX: { name: 'IDEX Corporation', category: 'Industrial' },
  IFF: { name: 'International Flavors', category: 'Materials' },
  INVH: { name: 'Invitation Homes Inc.', category: 'Real Estate' },
  IP: { name: 'International Paper Co.', category: 'Materials' },
  IPG: { name: 'Interpublic Group', category: 'Communication Services' },
  IQV: { name: 'IQVIA Holdings Inc.', category: 'Healthcare' },
  IR: { name: 'Ingersoll Rand Inc.', category: 'Industrial' },
  IRM: { name: 'Iron Mountain Inc.', category: 'Real Estate' },
  IT: { name: 'Gartner Inc.', category: 'Technology' },
  ITW: { name: 'Illinois Tool Works', category: 'Industrial' },
  IVZ: { name: 'Invesco Ltd.', category: 'Financial' },
  J: { name: 'Jacobs Solutions Inc.', category: 'Industrial' },
  JCI: { name: 'Johnson Controls', category: 'Industrial' },
  JKHY: { name: 'Jack Henry & Associates', category: 'Technology' },
  JNPR: { name: 'Juniper Networks Inc.', category: 'Technology' },
  K: { name: 'Kellanova', category: 'Consumer Defensive' },
  KDP: { name: 'Keurig Dr Pepper Inc.', category: 'Consumer Defensive' },
  KEY: { name: 'KeyCorp', category: 'Financial' },
  KEYS: { name: 'Keysight Technologies', category: 'Technology' },
  KHC: { name: 'Kraft Heinz Company', category: 'Consumer Defensive' },
  KIM: { name: 'Kimco Realty Corp.', category: 'Real Estate' },
  KMB: { name: 'Kimberly-Clark Corp.', category: 'Consumer Defensive' },
  KMI: { name: 'Kinder Morgan Inc.', category: 'Energy' },
  KMX: { name: 'CarMax Inc.', category: 'Consumer Cyclical' },
  KR: { name: 'Kroger Co.', category: 'Consumer Defensive' },
  L: { name: 'Loews Corporation', category: 'Financial' },
  LDOS: { name: 'Leidos Holdings Inc.', category: 'Industrial' },
  LEN: { name: 'Lennar Corporation', category: 'Consumer Cyclical' },
  LH: { name: 'Labcorp Holdings Inc.', category: 'Healthcare' },
  LHX: { name: 'L3Harris Technologies', category: 'Industrial' },
  LIN: { name: 'Linde plc', category: 'Materials' },
  LKQ: { name: 'LKQ Corporation', category: 'Consumer Cyclical' },
  LNT: { name: 'Alliant Energy Corp.', category: 'Utilities' },
  LUV: { name: 'Southwest Airlines Co.', category: 'Industrial' },
  LVS: { name: 'Las Vegas Sands Corp.', category: 'Consumer Cyclical' },
  LW: { name: 'Lamb Weston Holdings', category: 'Consumer Defensive' },
  LYB: { name: 'LyondellBasell Industries', category: 'Materials' },
  MAA: { name: 'Mid-America Apartment', category: 'Real Estate' },
  MAR: { name: 'Marriott International', category: 'Consumer Cyclical' },
  MAS: { name: 'Masco Corporation', category: 'Industrial' },
  MKC: { name: 'McCormick & Company', category: 'Consumer Defensive' },
  MKTX: { name: 'MarketAxess Holdings', category: 'Financial' },
  MLM: { name: 'Martin Marietta Materials', category: 'Materials' },
  MMC: { name: 'Marsh & McLennan', category: 'Financial' },
  MMM: { name: '3M Company', category: 'Industrial' },
  MNST: { name: 'Monster Beverage Corp.', category: 'Consumer Defensive' },
  MO: { name: 'Altria Group Inc.', category: 'Consumer Defensive' },
  MOH: { name: 'Molina Healthcare Inc.', category: 'Healthcare' },
  MOS: { name: 'Mosaic Company', category: 'Materials' },
  MPC: { name: 'Marathon Petroleum Corp.', category: 'Energy' },
  MPWR: { name: 'Monolithic Power Systems', category: 'Technology' },
  MRO: { name: 'Marathon Oil Corporation', category: 'Energy' },
  MSCI: { name: 'MSCI Inc.', category: 'Financial' },
  MSI: { name: 'Motorola Solutions', category: 'Technology' },
  MTB: { name: 'M&T Bank Corporation', category: 'Financial' },
  MTD: { name: 'Mettler-Toledo Intl.', category: 'Healthcare' },
  NCLH: { name: 'Norwegian Cruise Line', category: 'Consumer Cyclical' },
  NDSN: { name: 'Nordson Corporation', category: 'Industrial' },
  NEM: { name: 'Newmont Corporation', category: 'Materials' },
  NI: { name: 'NiSource Inc.', category: 'Utilities' },
  NOC: { name: 'Northrop Grumman Corp.', category: 'Industrial' },
  NRG: { name: 'NRG Energy Inc.', category: 'Utilities' },
  NSC: { name: 'Norfolk Southern Corp.', category: 'Industrial' },
  NTAP: { name: 'NetApp Inc.', category: 'Technology' },
  NTRS: { name: 'Northern Trust Corp.', category: 'Financial' },
  NUE: { name: 'Nucor Corporation', category: 'Materials' },
  NVR: { name: 'NVR Inc.', category: 'Consumer Cyclical' },
  NWL: { name: 'Newell Brands Inc.', category: 'Consumer Cyclical' },
  NWS: { name: 'News Corporation Class B', category: 'Communication Services' },
  NWSA: { name: 'News Corporation Class A', category: 'Communication Services' },
  NXPI: { name: 'NXP Semiconductors', category: 'Technology' },
  O: { name: 'Realty Income Corp.', category: 'Real Estate' },
  OGN: { name: 'Organon & Co.', category: 'Healthcare' },
  OKE: { name: 'ONEOK Inc.', category: 'Energy' },
  OMC: { name: 'Omnicom Group Inc.', category: 'Communication Services' },
  ON: { name: 'ON Semiconductor Corp.', category: 'Technology' },
  ORLY: { name: "O'Reilly Automotive", category: 'Consumer Cyclical' },
  OTIS: { name: 'Otis Worldwide Corp.', category: 'Industrial' },
  PAYC: { name: 'Paycom Software Inc.', category: 'Technology' },
  PAYX: { name: 'Paychex Inc.', category: 'Industrial' },
  PCAR: { name: 'PACCAR Inc.', category: 'Industrial' },
  PCG: { name: 'PG&E Corporation', category: 'Utilities' },
  PEAK: { name: 'Healthpeak Properties', category: 'Real Estate' },
  PEG: { name: 'Public Service Enterprise', category: 'Utilities' },
  PFG: { name: 'Principal Financial Group', category: 'Financial' },
  PGR: { name: 'Progressive Corporation', category: 'Financial' },
  PH: { name: 'Parker-Hannifin Corp.', category: 'Industrial' },
  PHM: { name: 'PulteGroup Inc.', category: 'Consumer Cyclical' },
  PKG: { name: 'Packaging Corp. of America', category: 'Materials' },
  PKI: { name: 'PerkinElmer Inc.', category: 'Healthcare' },
  PM: { name: 'Philip Morris Intl.', category: 'Consumer Defensive' },
  PNC: { name: 'PNC Financial Services', category: 'Financial' },
  PNR: { name: 'Pentair plc', category: 'Industrial' },
  PNW: { name: 'Pinnacle West Capital', category: 'Utilities' },
  POOL: { name: 'Pool Corporation', category: 'Consumer Cyclical' },
  PPG: { name: 'PPG Industries Inc.', category: 'Materials' },
  PPL: { name: 'PPL Corporation', category: 'Utilities' },
  PRU: { name: 'Prudential Financial', category: 'Financial' },
  PSA: { name: 'Public Storage', category: 'Real Estate' },
  PSX: { name: 'Phillips 66', category: 'Energy' },
  PTC: { name: 'PTC Inc.', category: 'Technology' },
  PWR: { name: 'Quanta Services Inc.', category: 'Industrial' },
  PXD: { name: 'Pioneer Natural Resources', category: 'Energy' },
  RCL: { name: 'Royal Caribbean Cruises', category: 'Consumer Cyclical' },
  RE: { name: 'Everest Re Group Ltd.', category: 'Financial' },
  REG: { name: 'Regency Centers Corp.', category: 'Real Estate' },
  RF: { name: 'Regions Financial Corp.', category: 'Financial' },
  RHI: { name: 'Robert Half Intl.', category: 'Industrial' },
  RJF: { name: 'Raymond James Financial', category: 'Financial' },
  RL: { name: 'Ralph Lauren Corp.', category: 'Consumer Cyclical' },
  RMD: { name: 'ResMed Inc.', category: 'Healthcare' },
  ROK: { name: 'Rockwell Automation', category: 'Industrial' },
  ROL: { name: 'Rollins Inc.', category: 'Industrial' },
  ROP: { name: 'Roper Technologies Inc.', category: 'Industrial' },
  RSG: { name: 'Republic Services Inc.', category: 'Industrial' },
  SHW: { name: 'Sherwin-Williams Co.', category: 'Materials' },
  SJM: { name: 'J.M. Smucker Company', category: 'Consumer Defensive' },
  SNA: { name: 'Snap-on Inc.', category: 'Industrial' },
  SPG: { name: 'Simon Property Group', category: 'Real Estate' },
  SPGI: { name: 'S&P Global Inc.', category: 'Financial' },
  SRE: { name: 'Sempra', category: 'Utilities' },
  STE: { name: 'STERIS plc', category: 'Healthcare' },
  STLD: { name: 'Steel Dynamics Inc.', category: 'Materials' },
  STT: { name: 'State Street Corp.', category: 'Financial' },
  STX: { name: 'Seagate Technology', category: 'Technology' },
  STZ: { name: 'Constellation Brands', category: 'Consumer Defensive' },
  SWK: { name: 'Stanley Black & Decker', category: 'Industrial' },
  SWKS: { name: 'Skyworks Solutions', category: 'Technology' },
  SYF: { name: 'Synchrony Financial', category: 'Financial' },
  SYK: { name: 'Stryker Corporation', category: 'Healthcare' },
  SYY: { name: 'Sysco Corporation', category: 'Consumer Defensive' },
  TAP: { name: 'Molson Coors Beverage', category: 'Consumer Defensive' },
  TDG: { name: 'TransDigm Group Inc.', category: 'Industrial' },
  TDY: { name: 'Teledyne Technologies', category: 'Industrial' },
  TECH: { name: 'Bio-Techne Corporation', category: 'Healthcare' },
  TEL: { name: 'TE Connectivity Ltd.', category: 'Technology' },
  TER: { name: 'Teradyne Inc.', category: 'Technology' },
  TFC: { name: 'Truist Financial Corp.', category: 'Financial' },
  TFX: { name: 'Teleflex Inc.', category: 'Healthcare' },
  TPR: { name: 'Tapestry Inc.', category: 'Consumer Cyclical' },
  TRGP: { name: 'Targa Resources Corp.', category: 'Energy' },
  TRMB: { name: 'Trimble Inc.', category: 'Technology' },
  TROW: { name: 'T. Rowe Price Group', category: 'Financial' },
  TRV: { name: 'Travelers Companies', category: 'Financial' },
  TSN: { name: 'Tyson Foods Inc.', category: 'Consumer Defensive' },
  TT: { name: 'Trane Technologies', category: 'Industrial' },
  TXT: { name: 'Textron Inc.', category: 'Industrial' },
  TYL: { name: 'Tyler Technologies Inc.', category: 'Technology' },
  UAL: { name: 'United Airlines Holdings', category: 'Industrial' },
  UDR: { name: 'UDR Inc.', category: 'Real Estate' },
  UHS: { name: 'Universal Health Services', category: 'Healthcare' },
  ULTA: { name: 'Ulta Beauty Inc.', category: 'Consumer Cyclical' },
  UPS: { name: 'United Parcel Service', category: 'Industrial' },
  URI: { name: 'United Rentals Inc.', category: 'Industrial' },
  USB: { name: 'U.S. Bancorp', category: 'Financial' },
  VFC: { name: 'V.F. Corporation', category: 'Consumer Cyclical' },
  VICI: { name: 'VICI Properties Inc.', category: 'Real Estate' },
  VLO: { name: 'Valero Energy Corp.', category: 'Energy' },
  VLTO: { name: 'Veralto Corporation', category: 'Industrial' },
  VMC: { name: 'Vulcan Materials Co.', category: 'Materials' },
  VRSK: { name: 'Verisk Analytics Inc.', category: 'Industrial' },
  VRSN: { name: 'VeriSign Inc.', category: 'Technology' },
  VTR: { name: 'Ventas Inc.', category: 'Real Estate' },
  VTRS: { name: 'Viatris Inc.', category: 'Healthcare' },
  WAB: { name: 'Westinghouse Air Brake', category: 'Industrial' },
  WAT: { name: 'Waters Corporation', category: 'Healthcare' },
  WBA: { name: 'Walgreens Boots Alliance', category: 'Consumer Defensive' },
  WDC: { name: 'Western Digital Corp.', category: 'Technology' },
  WEC: { name: 'WEC Energy Group Inc.', category: 'Utilities' },
  WELL: { name: 'Welltower Inc.', category: 'Real Estate' },
  WHR: { name: 'Whirlpool Corporation', category: 'Consumer Cyclical' },
  WM: { name: 'Waste Management Inc.', category: 'Industrial' },
  WMB: { name: 'Williams Companies Inc.', category: 'Energy' },
  WRB: { name: 'W.R. Berkley Corp.', category: 'Financial' },
  WRK: { name: 'WestRock Company', category: 'Materials' },
  WST: { name: 'West Pharmaceutical', category: 'Healthcare' },
  WTW: { name: 'Willis Towers Watson', category: 'Financial' },
  WY: { name: 'Weyerhaeuser Company', category: 'Real Estate' },
  WYNN: { name: 'Wynn Resorts Ltd.', category: 'Consumer Cyclical' },
  XEL: { name: 'Xcel Energy Inc.', category: 'Utilities' },
  XYL: { name: 'Xylem Inc.', category: 'Industrial' },
  YUM: { name: 'Yum! Brands Inc.', category: 'Consumer Cyclical' },
  ZBH: { name: 'Zimmer Biomet Holdings', category: 'Healthcare' },
  ZION: { name: 'Zions Bancorporation', category: 'Financial' },
  ZTS: { name: 'Zoetis Inc.', category: 'Healthcare' },
};

export function getAssetInfo(symbol: string): { name: string; category: string } {
  return ASSET_INFO[symbol] || {
    name: symbol,
    category: getAssetType(symbol) === 'stock'
      ? 'Stock'
      : getAssetType(symbol).charAt(0).toUpperCase() + getAssetType(symbol).slice(1),
  };
}
